set(LV_EDITOR_PROJECT_SOURCES)
list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/power_meter_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/power_meter_ui.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_active_power_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_apparent_power_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_energy_data_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_function_menu_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_current_0_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_current_1_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_current_2_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_current_3_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_current_4_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_current_5_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_current_6_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_current_7_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_voltage_1_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_voltage_2_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_voltage_3_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_voltage_4_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_voltage_5_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_voltage_6_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_spectrum_table_voltage_7_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_waveform_current_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_waveform_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_harmonic_waveform_voltage_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_line_voltage_demand_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_paid_harmonic_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_paid_max_demand_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_phase_frequency_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_power_quality_analysis_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_reactive_power_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_address_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_alarm_threshold_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_brightness_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_factory_reset_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_ratio_ct_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_ratio_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_ratio_pt_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_system_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_theme_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_uart_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_upgrade_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_wifi_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_wifi_sta_gen.c)